# Generated by Django 4.2.24 on 2025-09-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
