# Generated by Django 4.2.24 on 2025-09-19 07:51

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='display_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
