# Generated by Django 4.2.24 on 2025-09-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_display_datetime_alter_about_content'),
        ('about', '0003_about_display_datetime'),
    ]

    operations = [
    ]
